using System.Reflection;

// NB! this file is automatically generated. All manual changes will be lost on build.
// Check ~/_tools/Nortal.Utilities.AssemblyVersioning.props file for other available algorithms and supported attributes.

// Generated based on assembly version: 0.10.1.0
[assembly: AssemblyInformationalVersion("0.10.1-Debug-20150216-1629")] // algorithm: NugetSemanticVersionGenerator
[assembly: AssemblyFileVersion("0.10.50216.1629")] // algorithm: HumanReadable2SlotTimestampGenerator
[assembly: AssemblyConfiguration("Debug (on UTC2015-02-16T16:29:30 by imrep at DELL688)")] // algorithm: HumanReadableBuildInfoGenerator
